### PR TITLE
Update esprima version

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by Swatinem** [comment]
Thank you very much for your last few patches :-)

**Comment by amilajack** [comment]
@Swatinem Thanks! I'm thinking of working on a JS static analysis tool. Do you think it would be possible to check for memory leaks using the CFG produced from this tool?

**Comment by Swatinem** [comment]
I don’t really have experience with such an analysis. But if its generally solvable with a CFG, esgraph may be up for it.

**Comment by ChristianMurphy** [comment]
@amilajack memory checking *can* be done directly with cfg, but usually cfg+[ssa](https://en.wikipedia.org/wiki/Static_single_assignment_form) provides a better abstraction to work with.
E.G. https://github.com/js-js/ssa.js

**Pull request merged**
