### PR TITLE
refactor esgraph using ES2017 features

### PR DESCRIPTION
**Pull request by ChristianMurphy**
Leverage ES2017 syntax features and syntax sugar.
*Hopefully* making the code easier to read and maintain.

#### Other changes

* replace `jshint` with `eslint`
* use nyc, the official istanbul cli
* automatically format with prettier
* apply airbnb code style
* test on CI with node 8+
* replace `make` with npm scripts

### CODE REVIEW

**Comment by Swatinem** [comment]
This is amazing stuff @ChristianMurphy !
would have been good to split this up into multiple commits though. Its hard to review actual code changes next to all the reformatting.

Anyway, I’m not really maintaining this anymore anyway. Since you put in so much effort, would you like to take over?

**Comment by ChristianMurphy** [comment]
> would have been good to split this up into multiple commits though. Its hard to review actual code changes next to all the reformatting.

Yeah, sorry about that, with the autoformatter and autofixing being run during the, all the changes got mixed together. :disappointed: 
Good news though, now that there is a formatter in place, churn should be reduced. :slightly_smiling_face: 

> Anyway, I’m not really maintaining this anymore anyway. Since you put in so much effort, would you like to take over?

Sure, I'd be happy to help maintain the project. :+1:

**Comment by Swatinem** [comment]
I invited you to the project. can you give me your npm username as well?

**Comment by ChristianMurphy** [comment]
Thanks!
My NPM username is [christianmurphy](https://www.npmjs.com/~christianmurphy)

**Comment by Swatinem** [comment]
Ok, you should also be added as second owner on npm :-)
Feel free to merge and publish.

I really appreciate your interest in picking this up, thanks!

**Pull request merged**
